const api = window.projectManager;
const state = { projects: [], tasks: [], candidates: [], settings: {}, activeView: 'overview', detail: null, loading: true, error: '' };
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const formatDate = (value) => value && value !== '—' ? value : '暂无';
const statusLabel = { todo: '待办', doing: '进行中', blocked: '阻塞', done: '已完成' };
const health = (project) => project.dirtyCount === null ? ['严重', 'critical'] : project.dirtyCount > 10 ? ['警告', 'warning'] : project.dirtyCount > 0 ? ['注意', 'attention'] : ['正常', 'healthy'];

function render() {
  document.body.dataset.theme = state.settings.theme || 'dark';
  document.body.innerHTML = `
    <div class="app-shell">
      <aside class="sidebar">
        <div class="brand"><span class="brand-mark">A</span><div><strong>ALIPRO</strong><small>项目管理台</small></div></div>
        <div class="workspace-switch"><span class="eyebrow">当前工作区</span><strong>默认工作区</strong><span class="muted">${state.projects.length} 个已纳入项目</span></div>
        <nav class="nav-list">
          ${navItem('overview', '⌂', '总览')}${navItem('projects', '▦', '项目')}${navItem('tasks', '✓', '内置任务')}${navItem('history', '⌁', '历史趋势')}${navItem('logs', '≡', '操作记录')}${navItem('settings', '⚙', '设置')}
        </nav>
        <div class="sidebar-bottom"><div class="offline-pill"><i></i> 本地优先 · 离线可用</div><small>数据保存在本机</small></div>
      </aside>
      <main class="main-content">
        <header class="topbar"><div><span class="eyebrow">开发控制中心 / ${state.activeView === 'overview' ? '总览' : viewTitle()}</span><h1>${state.activeView === 'overview' ? '项目状态总览' : viewTitle()}</h1></div><div class="top-actions"><span class="sync-time">最后刷新 ${state.lastRefresh ? formatDate(state.lastRefresh) : '刚刚'}</span><button class="button ghost" id="refresh">↻ 立即刷新</button><button class="button primary" id="export">导出备份</button></div></header>
        ${state.error ? `<div class="alert critical">${escapeHtml(state.error)}</div>` : ''}
        ${state.loading ? '<div class="loading">正在读取本机项目数据…</div>' : viewContent()}
      </main>
    </div>`;
  bindEvents();
}
function navItem(id, icon, label) { return `<button class="nav-item ${state.activeView === id ? 'active' : ''}" data-view="${id}"><span>${icon}</span>${label}${id === 'tasks' && state.tasks.filter((task) => task.status !== 'done').length ? `<b>${state.tasks.filter((task) => task.status !== 'done').length}</b>` : ''}</button>`; }
function viewTitle() { return { projects: '项目列表', tasks: '内置任务看板', history: '历史趋势', logs: '操作记录', settings: '设置' }[state.activeView] || '总览'; }
function viewContent() { if (state.activeView === 'projects') return projectsView(true); if (state.activeView === 'tasks') return tasksView(); if (state.activeView === 'history') return historyView(); if (state.activeView === 'logs') return logsView(); if (state.activeView === 'settings') return settingsView(); return overviewView(); }
function overviewView() {
  const dirty = state.projects.filter((p) => p.dirtyCount > 0).length; const stale = state.projects.filter((p) => !p.gitAvailable).length; const openTasks = state.tasks.filter((task) => task.status !== 'done').length;
  return `<section class="content-grid"><div class="hero-card"><div><span class="eyebrow">今日重点</span><h2>${openTasks ? `有 ${openTasks} 项开发任务待处理` : '今天没有未处理任务'}</h2><p>${dirty ? `${dirty} 个项目存在未提交修改。` : '所有已纳入项目工作区整洁。'}${stale ? `另有 ${stale} 个项目暂时无法读取 Git。` : ''}</p></div><div class="hero-orbit"><span>${state.projects.length}</span><small>项目</small></div></div>
    <div class="metrics"><metric-card label="项目总数" value="${state.projects.length}" hint="已纳入工作区" icon="▦"/><metric-card label="未提交修改" value="${dirty}" hint="需要关注的项目" icon="◐" tone="${dirty ? 'warning' : ''}"/><metric-card label="待办任务" value="${openTasks}" hint="内置看板" icon="✓" tone="${openTasks ? 'attention' : ''}"/><metric-card label="本地可用率" value="${state.projects.length ? Math.round((state.projects.length - stale) / state.projects.length * 100) : 0}%" hint="Git 读取成功" icon="⌁" tone="${stale ? 'critical' : ''}"/></div>
    <div class="section-head"><div><span class="eyebrow">工作区项目</span><h2>项目健康一览</h2></div><button class="text-button" data-view="projects">查看全部 →</button></div>${projectsView(false)}
    <div class="section-head task-head"><div><span class="eyebrow">今日开发节奏</span><h2>内置任务</h2></div><button class="text-button" data-view="tasks">打开看板 →</button></div>${taskPreview()}</section>`;
}
function metricCard(label, value, hint, icon, tone = '') { return `<div class="metric-card ${tone}"><div class="metric-icon">${icon}</div><span>${label}</span><strong>${value}</strong><small>${hint}</small></div>`; }
function projectsView(full) { const list = full ? state.projects : state.projects.slice(0, 6); return `${full ? '<div class="list-toolbar"><p>根据 Git remote 自动读取本地项目信息。</p><div><button class="button ghost" id="scan">扫描目录</button> <button class="button primary" id="choose-project">＋ 手动添加项目</button></div></div>' : ''}<div class="project-grid">${list.length ? list.map(projectCard).join('') : emptyProjects()}</div>${!full && state.projects.length > 6 ? `<div class="more-note">还有 ${state.projects.length - 6} 个项目未显示</div>` : ''}`; }
function projectCard(project) { const [label, tone] = health(project); const gitee = project.gitee; return `<article class="project-card ${state.detail === project.id ? 'selected' : ''}"><div class="project-card-head"><div class="project-title"><span class="repo-icon">⌘</span><div><h3>${escapeHtml(project.name)}</h3><small title="${escapeHtml(project.path)}">${escapeHtml(project.path)}</small></div></div><div class="card-actions"><button title="收藏" data-toggle="favorite" data-id="${project.id}" class="icon-button ${project.favorite ? 'on' : ''}">★</button><button title="置顶" data-toggle="pinned" data-id="${project.id}" class="icon-button ${project.pinned ? 'on' : ''}">⌃</button></div></div><div class="health-row"><span class="health-dot ${tone}"></span><strong>${label}</strong><span class="branch">⑂ ${escapeHtml(project.branch)}</span></div><div class="project-stats"><div><small>工作区</small><strong>${project.dirtyCount === null ? '不可用' : project.dirtyCount ? `${project.dirtyCount} 项修改` : '干净'}</strong></div><div><small>最近提交</small><strong>${escapeHtml(project.lastCommit)}</strong></div><div><small>远程</small><strong title="${escapeHtml(project.remote)}">${project.remote ? '已关联' : '未关联'}</strong></div></div><p class="commit-line">${escapeHtml(project.commitMessage)}</p><div class="card-footer"><button class="text-button" data-open-project="${project.id}">查看详情</button><button class="mini-button" data-gitee-sync="${project.id}">同步 Gitee</button><button class="mini-button" data-git-operation="fetch" data-id="${project.id}">Fetch</button><button class="mini-button" data-git-operation="pull" data-id="${project.id}">Pull</button><button class="mini-button" data-terminal="${escapeHtml(project.path)}">终端</button><button class="mini-button" data-open="${escapeHtml(project.path)}">目录</button></div>${state.detail === project.id ? `<div class="project-detail"><div><span>Gitee</span><strong>${gitee?.repo?.fullName || (gitee?.error || '尚未同步')}</strong></div><div><span>PR</span><strong>${gitee?.prs?.length ?? '—'}</strong></div><div><span>Issues</span><strong>${gitee?.issues?.length ?? '—'}</strong></div><div><span>Milestones</span><strong>${gitee?.milestones?.length ?? '—'}</strong></div>${gitee?.syncedAt ? `<small>上次同步：${formatDate(gitee.syncedAt)}${gitee.error ? ` · 暂不可用：${escapeHtml(gitee.error)}` : ''}</small>` : ''}</div>` : ''}</article>`; }
function emptyProjects() { return `<div class="empty-state"><div class="empty-icon">⌂</div><h3>还没有纳入项目</h3><p>可以先扫描桌面、文档和下载目录，确认后加入项目总览。</p><button class="button primary" id="scan">立即扫描</button></div>`; }
function taskPreview() { return `<div class="task-preview">${state.tasks.slice(0, 4).map(taskRow).join('') || '<div class="empty-line">还没有内置任务</div>'}</div>`; }
function taskRow(task) { return `<div class="task-row"><span class="task-status ${task.status}"></span><div><strong>${escapeHtml(task.title)}</strong><small>${escapeHtml(task.description || '无描述')}</small></div><span class="status-label ${task.status}">${statusLabel[task.status] || task.status}</span></div>`; }
function tasksView() { const groups = ['todo', 'doing', 'blocked', 'done']; return `<div class="board-toolbar"><p>内置看板与项目文档、Gitee Issues/Milestones 并列展示，来源后续接入。</p><button class="button primary" id="new-task">＋ 新建任务</button></div><div class="task-board">${groups.map((group) => `<section class="task-column" data-status="${group}"><div class="column-head"><h3>${statusLabel[group]}</h3><span>${state.tasks.filter((task) => task.status === group).length}</span></div>${state.tasks.filter((task) => task.status === group).map((task) => `<article class="task-card" draggable="true" data-task-id="${task.id}"><div class="task-card-top"><span class="drag-handle">⠿</span><button class="delete-task" data-delete-task="${task.id}">×</button></div><h4>${escapeHtml(task.title)}</h4><p>${escapeHtml(task.description || '暂无描述')}</p><select data-task-status="${task.id}">${groups.map((option) => `<option value="${option}" ${task.status === option ? 'selected' : ''}>${statusLabel[option]}</option>`).join('')}</select></article>`).join('') || '<div class="column-empty">拖拽任务到这里</div>'}</section>`).join('')}</div>`; }
function logsView() { return `<div class="board-toolbar"><p>所有本地 Git 操作和同步过程都会记录在本机。</p><div><button class="button ghost" id="clear-queue">清空未执行队列</button><button class="button primary" id="show-queue">查看队列</button></div></div><div class="logs-card"><div class="table-head"><span>时间</span><span>操作</span><span>项目</span><span>结果</span><span>命令</span></div><div id="logs-body"><div class="loading">正在读取操作记录…</div></div></div>`; }
function settingsView() { const roots = state.settings.scanRoots || []; return `<div class="settings-grid"><section class="settings-card"><span class="eyebrow">外观</span><h2>界面主题</h2><p>支持深色和浅色主题切换。</p><div class="segmented"><button data-theme="dark" class="${state.settings.theme === 'dark' ? 'active' : ''}">深色</button><button data-theme="light" class="${state.settings.theme === 'light' ? 'active' : ''}">浅色</button></div></section><section class="settings-card"><span class="eyebrow">本地扫描</span><h2>扫描目录</h2><p>启动时扫描，并允许你随时调整范围。</p><div class="roots-list">${roots.map((root, index) => `<div><span>${escapeHtml(root)}</span><button data-remove-root="${index}">移除</button></div>`).join('')}</div><button class="button ghost" id="add-root">＋ 添加目录</button></section><section class="settings-card"><span class="eyebrow">数据</span><h2>本机数据</h2><p>项目、任务和日志保存在本机专用数据库中。</p><button class="button primary" id="export-settings">导出 JSON 备份</button><button class="button ghost" id="export-csv">导出 CSV</button><button class="button ghost" id="export-zip">完整 ZIP 备份</button></section></div>`; }
function historyView() { const points = state.metrics || []; const max = Math.max(1, ...points.map((item) => item.dirty_count)); return `<div class="board-toolbar"><p>当前状态每次刷新保存，趋势数据长期保存在本机。</p><div><button class="button ghost" id="export-csv">导出 CSV</button><button class="button primary" id="export-zip">完整 ZIP 备份</button></div></div><div class="trend-card"><div class="trend-head"><div><span class="eyebrow">工作区变化</span><h2>未提交项目趋势</h2></div><span>${points.length} 个快照</span></div><div class="sparkline">${points.slice(-30).map((item) => `<div class="bar" style="height:${Math.max(8, Math.round((item.dirty_count / max) * 130))}px" title="${escapeHtml(item.captured_at)} · ${item.dirty_count} 个项目有修改"></div>`).join('') || '<div class="empty-line">刷新项目后开始记录趋势</div>'}</div></div><div class="logs-card"><div class="table-head"><span>时间</span><span>项目数</span><span>未提交</span><span>待办任务</span><span>Git 不可用</span></div>${points.slice(-20).reverse().map((item) => `<div class="table-row"><span>${escapeHtml(item.captured_at)}</span><span>${item.project_count}</span><span>${item.dirty_count}</span><span>${item.open_task_count}</span><span>${item.unavailable_count}</span></div>`).join('')}</div>`; }

function bindEvents() {
  document.querySelectorAll('[data-view]').forEach((el) => el.addEventListener('click', async () => { state.activeView = el.dataset.view; if (state.activeView === 'history') state.metrics = await api.metrics(); render(); if (state.activeView === 'logs') loadLogs(); }));
  $('#refresh')?.addEventListener('click', refresh); $('#export')?.addEventListener('click', () => api.exportData()); $('#export-settings')?.addEventListener('click', () => api.exportData()); $('#export-csv')?.addEventListener('click', () => api.exportCsv()); $('#export-zip')?.addEventListener('click', () => api.exportZip()); $('#scan')?.addEventListener('click', scan); $('#choose-project')?.addEventListener('click', async () => { const projects = await api.chooseProject(); if (projects) { state.projects = projects; state.lastRefresh = new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }); render(); } }); $('#add-root')?.addEventListener('click', addRoot); $('#new-task')?.addEventListener('click', newTask); $('#show-queue')?.addEventListener('click', async () => { const queue = await api.queue(); alert(queue.queued.length ? queue.queued.map((item) => `${item.project} · ${item.operation}\n${item.command}`).join('\n\n') : '当前没有排队中的操作。'); }); $('#clear-queue')?.addEventListener('click', async () => { await api.clearQueue(); alert('未执行队列已清空。'); });
  document.querySelectorAll('[data-toggle]').forEach((el) => el.addEventListener('click', async () => { await api.toggleProject({ id: Number(el.dataset.id), field: el.dataset.toggle }); await refresh(); }));
  document.querySelectorAll('[data-open]').forEach((el) => el.addEventListener('click', () => api.openPath(el.dataset.open))); document.querySelectorAll('[data-terminal]').forEach((el) => el.addEventListener('click', () => api.openTerminal(el.dataset.terminal))); document.querySelectorAll('[data-gitee-sync]').forEach((el) => el.addEventListener('click', async () => { const project = state.projects.find((item) => item.id === Number(el.dataset.giteeSync)); if (!project) return; el.textContent = '同步中…'; const snapshot = await api.syncGitee(project); project.gitee = snapshot; render(); })); document.querySelectorAll('[data-git-operation]').forEach((el) => el.addEventListener('click', () => runGitOperation(Number(el.dataset.id), el.dataset.gitOperation)));
  document.querySelectorAll('[data-open-project]').forEach((el) => el.addEventListener('click', () => { state.detail = Number(el.dataset.openProject); state.activeView = 'projects'; render(); }));
  document.querySelectorAll('[data-delete-task]').forEach((el) => el.addEventListener('click', async () => { state.tasks = await api.deleteTask(Number(el.dataset.deleteTask)); render(); })); document.querySelectorAll('[data-task-status]').forEach((el) => el.addEventListener('change', async () => { const task = state.tasks.find((item) => item.id === Number(el.dataset.taskStatus)); task.status = el.value; state.tasks = await api.updateTask(task); render(); }));
  document.querySelectorAll('[data-theme]').forEach((el) => el.addEventListener('click', async () => { state.settings.theme = el.dataset.theme; await api.saveSettings({ theme: state.settings.theme }); render(); })); document.querySelectorAll('[data-remove-root]').forEach((el) => el.addEventListener('click', async () => { state.settings.scanRoots.splice(Number(el.dataset.removeRoot), 1); await api.saveSettings({ scanRoots: state.settings.scanRoots }); render(); }));
  document.querySelectorAll('.task-card').forEach((card) => { card.addEventListener('dragstart', (event) => event.dataTransfer.setData('text/plain', card.dataset.taskId)); }); document.querySelectorAll('.task-column').forEach((column) => column.addEventListener('dragover', (event) => event.preventDefault())); document.querySelectorAll('.task-column').forEach((column) => column.addEventListener('drop', async (event) => { event.preventDefault(); const task = state.tasks.find((item) => item.id === Number(event.dataTransfer.getData('text/plain'))); if (!task) return; task.status = column.dataset.status; state.tasks = await api.updateTask(task); render(); }));
}
async function refresh() { state.loading = true; render(); try { const data = await api.refresh(); state.projects = data.projects; state.candidates = data.candidates; state.lastRefresh = new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }); state.error = ''; } catch (error) { state.error = error.message; } state.loading = false; render(); if (state.activeView === 'logs') loadLogs(); }
async function scan() { const found = await api.scan(); state.candidates = found; if (!found.length) return alert('没有发现新的项目目录。'); const selected = confirm(`发现 ${found.length} 个候选项目，是否全部加入？\n\n${found.slice(0, 8).map((item) => item.name).join('\n')}`); if (selected) { for (const item of found) await api.addProject(item.path); await refresh(); } }
async function addRoot() { const root = prompt('请输入要扫描的目录完整路径：'); if (!root) return; if (!state.settings.scanRoots.includes(root)) state.settings.scanRoots.push(root); await api.saveSettings({ scanRoots: state.settings.scanRoots }); render(); }
async function newTask() { const title = prompt('任务标题：'); if (!title) return; const description = prompt('任务描述（可选）：') || ''; state.tasks = await api.createTask({ title, description }); render(); }
async function loadLogs() { const logs = await api.logs(); const body = $('#logs-body'); if (!body) return; body.innerHTML = logs.length ? logs.map((log) => `<div class="table-row"><span>${escapeHtml(log.finished_at || log.started_at)}</span><span>${escapeHtml(log.operation)}</span><span>${escapeHtml(log.project_id || '—')}</span><span class="status-label ${log.status === 'success' ? 'done' : 'blocked'}">${log.status === 'success' ? '成功' : '失败'}</span><code>${escapeHtml(log.command || '')}</code></div>`).join('') : '<div class="empty-line">暂无操作记录</div>'; }
async function runGitOperation(projectId, operation) { const project = state.projects.find((item) => item.id === projectId); if (!project) return; const argsByOperation = { fetch: ['fetch', '--all', '--prune'], pull: ['pull', '--ff-only'], push: ['push'] }; const args = argsByOperation[operation]; if (!args) return; let result = await api.runGit({ project, operation, args }); if (result.needsConfirmation) { const approved = confirm(`高风险操作：${result.operation}\n\n命令：${result.command}\n影响：${result.impact}\n\n是否继续？`); if (!approved) return; result = await api.runGit({ project, operation, args, confirmed: true }); } if (result.ok) { await api.notify({ title: 'ALIPRO 项目管理台', body: `${project.name} · ${operation} 已完成` }); await refresh(); } else { alert(`${operation} 失败：\n${result.stderr || result.stdout || '未知错误'}`); } }
async function loadLogs() { const logs = await api.logs(); const body = $('#logs-body'); if (!body) return; body.innerHTML = logs.length ? logs.map((log) => `<div class="table-row"><span>${escapeHtml(log.finished_at || log.started_at)}</span><span>${escapeHtml(log.operation)}</span><span>${escapeHtml(log.project_id || '—')}</span><span class="status-label ${log.status === 'success' ? 'done' : 'blocked'}">${log.status === 'success' ? '成功' : '失败'}</span><code>${escapeHtml(log.command || '')}</code></div>`).join('') : '<div class="empty-line">暂无操作记录</div>'; }
api.onExportRequest(() => api.exportData());
api.bootstrap().then(async (data) => { state.projects = data.projects; state.tasks = data.tasks; state.candidates = data.candidates; state.settings = data.settings; state.metrics = await api.metrics(); state.loading = false; state.lastRefresh = new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }); render(); }).catch((error) => { state.loading = false; state.error = error.message; render(); });
setInterval(async () => { if (!document.hidden) await refresh(); }, 10 * 60 * 1000);
